spring.application.name=rolebaseauth
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.error.include-message=always
server.error.include-binding-errors=always
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME}
aws.token = ${AWS_TOKEN}
aws.region=${AWS_REGION:eu-north-1}
aws.access.key.id = ${AWS_ACCESS_KEY_ID} 
aws.secret.key.id = ${AWS_SECRET_ACCESS_KEY} 
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

